sonar.projectKey=MystenLabs_hashi-ts-sdk
sonar.organization=mystenlabs

sonar.projectName=hashi-ts-sdk

sonar.sources=src
sonar.tests=test

sonar.exclusions=src/contracts/**,src/index.ts
sonar.coverage.exclusions=src/contracts/**,src/index.ts
sonar.cpd.exclusions=src/contracts/**,test/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
